#!/bin/bash
clear
echo -e "\033[1;33mINICIANDO ACTUALIZACIÓN NoxuraSSH \033[0m"
sleep 2s
# Mismo repo que Install/list (edita en Install/list o exporta aqui):
SSHPLUS_GH_USER_REPO="${SSHPLUS_GH_USER_REPO:-soportecrisdev/SCRIP_CRISDEV}"
case "${SSHPLUS_GH_USER_REPO}" in
usuario/tu-repo|tu_usuario/tu_repo) SSHPLUS_GH_USER_REPO="soportecrisdev/SCRIP_CRISDEV" ;;
esac
SSHPLUS_GH_BRANCH="${SSHPLUS_GH_BRANCH:-main}"
SSHPLUS_RAW="https://raw.githubusercontent.com/${SSHPLUS_GH_USER_REPO}/${SSHPLUS_GH_BRANCH}"
tmp=$(mktemp)
if wget -qO "$tmp" "${SSHPLUS_RAW}/script/install"; then
	chmod +x "$tmp"
	bash "$tmp"
	rm -f "$tmp"
else
	echo -e "\033[1;31mFallo al descargar script/install. Revise SSHPLUS_GH_USER_REPO / rama en GitHub.\033[0m"
	rm -f "$tmp"
	exit 1
fi
