#!/bin/bash
# lang=es badvpn3
fun_badvpn() {
    clear
    echo -e "\E[44;1;37m            GESTIONAR BADVPN-UDP             \E[0m"
    if pgrep -f 'badvpn-udpgw|udpvpn' 1>/dev/null 2>/dev/null; then
        echo -e "\033[1;33mPUERTOS\033[1;37m: \033[1;32m$((ss -ulpn 2>/dev/null | grep -E 'badvpn|udpvpn' || netstat -nplu 2>/dev/null | grep 'badvpn') | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(pgrep -f 'badvpn-udpgw|udpvpn' > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
echo -e "\033[01;34m===================================================================="
    echo -e "\033[1;34m[\033[1;37m01 •\033[1;34m]\033[1;37m  > \033[1;33m\033[1;37m( HABILITAR PUERTO UDP PARA JUEGOS/VOIP. ) $var_sks1 \033[0m"
    echo -e "\033[1;34m[\033[1;37m02 •\033[1;34m]\033[1;37m  > \033[1;33m\033[1;37m( ABRIR NUEVOS PUERTOS UDP. )\033[0m"
    echo -e "\033[1;34m[\033[1;37m00 •\033[1;34m]\033[1;37m  > \033[1;37m( VOLVER AL MENU ANTERIOR. )\033[0m"
echo -e "\033[01;34m===================================================================="
    echo -ne "\033[1;37m[ELIJA UN NUMERO]\033[1;37m: "; read resposta
    if [[ "$resposta" = '1' ]]; then
        if pgrep -f 'badvpn-udpgw|udpvpn' 1>/dev/null 2>/dev/null; then
            clear
            echo -e "\E[41;1;37m             BADVPN-UDP              \E[0m"
            echo ""
            fun_stopbad () {
                sleep 1
                for pidudpvpn in $(screen -ls | grep ".udpvpn" | awk {'print $1'}); do
                    screen -r -S "$pidudpvpn" -X quit
				done
                [[ $(grep -wc "udpvpn" /etc/autostart) != '0' ]] && {
                    sed -i '/udpvpn/d' /etc/autostart
                }
                sleep 1
                screen -wipe >/dev/null
            }
            echo -e "\033[1;33mDETENIENDO BADVPN-UDP\033[1;33m"
            echo ""
            fun_stopbad
            echo -e "\033[1;32mBADVPN-UDP APAGADO CORRECTAMENTE.\033[1;33m"
            sleep 2s
            fun_badvpn
        else
            clear
            echo -e "\033[1;32mINICIANDO BADVPN-UDP... \033[0m\n"
            fun_udpon () {
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 16384 --max-connections-for-client 5 --client-socket-sndbuf 16384 --udp-mtu 9000
                [[ $(grep -wc "udpvpn" /etc/autostart) = '0' ]] && {
                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 16384 --max-connections-for-client 5 --client-socket-sndbuf 16384 --udp-mtu 9000" >> /etc/autostart
                } || {
                    sed -i '/udpvpn/d' /etc/autostart
                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 16384 --max-connections-for-client 5 --client-socket-sndbuf 16384 --udp-mtu 9000" >> /etc/autostart
                }
                sleep 1
            }
            inst_udp () {
                [[ -e "/bin/badvpn-udpgw" ]] && {
                    sleep 0.1
                } || {
                    cd $HOME
                    wget -qO badvpn-udpgw "https://raw.githubusercontent.com/soportecrisdev/SCRIP_CRISDEV/main/badvpn/badvpn-udpgw" > /dev/null 2>&1
                    mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
                    chmod +x /bin/badvpn-udpgw
                }
            }
            inst_udp
            fun_udpon
            echo -e "\033[1;32mBADVPN-UDP ACTIVADO CORRECTAMENTE.\033[1;33m"
            sleep 3
            fun_badvpn
        fi
    elif [[ "$resposta" = '2' ]]; then
        if pgrep -f 'badvpn-udpgw|udpvpn' 1>/dev/null 2>/dev/null; then
            clear
            echo -e "\E[44;1;37m            BADVPN-UDP             \E[0m"
            echo ""
            echo -ne "\033[1;33m¿QUÉ PUERTO DESEA USAR \033[1;33m?\033[1;37m: "
            read porta
            [[ -z "$porta" ]] && {
                echo ""
                echo -e "\033[1;31mPuerto no valido!"
                sleep 2
                clear
                badvpn
            }
            echo ""
            echo -e "\033[1;33mINICIANDO BADVPN-UDP EN PUERTO \033[1;36m$porta\033[1;33m"
            fun_abrirptbad() {
                sleep 1
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 16384 --max-connections-for-client 5 --client-socket-sndbuf 16384 --udp-mtu 9000
                sleep 1
            }
            fun_abrirptbad
            echo ""
            echo -e "\033[1;32mBADVPN-UDP ACTIVADO CORRECTAMENTE\033[1;33m"
            sleep 2
            fun_badvpn
        else
            clear
            echo -e "\033[1;31mFUNCION NO DISPONIBLE\n\n\033[1;33mACTIVE BADVPN-UDP PRIMERO.\033[1;33m"
            sleep 2
            fun_badvpn
        fi
    elif [[ "$resposta" = '0' ]]; then
        echo ""
        menu
    else
        echo ""
        echo -e "\033[1;31mOpcion no valida!\033[0m"
        sleep 1
        fun_badvpn
    fi
}
fun_badvpn
