#!/bin/bash
# lang=es rootpass

echo -e "\033[1;31m¡ATENCIÓN!\033[0m"
echo " "
echo -e "\033[1;33mEsta clave se usará para acceder a su servidor.
\033[0m"
echo -e "\033[1;32mESCRIBA LA NUEVA CLAVE \033[1;32m
para continuar...\033[1;31m\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31mCLAVE MODIFICADA CORRECTAMENTE.\033[0m"
sleep 5s
cd
clear

