#!/bin/bash
# lang=es sshmonitor
_mon="${BASH_SOURCE[0]:-$0}"
if ! grep -q 'lang=es sshmonitor' "$_mon" 2>/dev/null; then
	wget -qO /bin/sshmonitor "https://raw.githubusercontent.com/soportecrisdev/SCRIP_CRISDEV/main/Modulos/sshmonitor" && chmod +x /bin/sshmonitor && exec /bin/sshmonitor
fi

clear
[[ -e /usr/lib/licence ]] || exit 0

database="/root/usuarios.db"
SSHPLUS_CYAN=$'\033[38;2;76;228;255m'
SSHPLUS_NUM=$'\033[1;38;2;0;255;127m'
line() { echo -e "${SSHPLUS_CYAN}============================================================\033[0m"; }
title() {
	local text="$1" cols pad
	cols="$(tput cols 2>/dev/null || echo 60)"
	[[ "$cols" =~ ^[0-9]+$ ]] || cols=60
	[[ "$cols" -gt 60 ]] && cols=60
	[[ "$cols" -lt 40 ]] && cols=40
	[[ ${#text} -gt "$cols" ]] && text="${text:0:cols}"
	pad=$(( (cols - ${#text}) / 2 ))
	[[ "$pad" -lt 0 ]] && pad=0
	printf '%*s%b\033[1m%s\033[0m\n' "$pad" "" "$SSHPLUS_CYAN" "$text"
}
[[ -s "$database" ]] || {
	line
	echo -e "${SSHPLUS_CYAN}\033[1mUSUARIOS:          ESTADO:       CONECTADOS:       TIEMPO:\033[0m"
	line
	echo -e "\033[1;33mNo hay usuarios creados por la script.\033[0m"
	line
	echo -e " ${SSHPLUS_NUM}[0]\033[0m \033[1;37m> VOLVER\033[0m"
	line
	echo ""
	echo -ne "\033[1;32mOpcion\033[1;33m: \033[0m"; read -r _back
	exit 0
}

valid_sshplus_user() {
	local user="$1" uid
	[[ -z "$user" || "$user" == "nobody" || "$user" == systemd-* || "$user" == "_"* ]] && return 1
	uid="$(getent passwd "$user" 2>/dev/null | awk -F: '{print $3}')"
	[[ "$uid" =~ ^[0-9]+$ && "$uid" -ge 1000 ]]
}

fun_drop() {
	local port_dropbear log loginsukses pids pid pidlogs i pidend login PID user waktu
	port_dropbear="$(ps aux | grep dropbear | awk 'NR==1 {print $17}')"
	log=/var/log/auth.log
	loginsukses='Password auth succeeded'
	pids="$(ps ax | grep dropbear | grep " $port_dropbear" | awk -F" " '{print $1}')"
	for pid in $pids; do
		pidlogs="$(grep "$pid" "$log" 2>/dev/null | grep "$loginsukses" | awk -F" " '{print $3}')"
		i=0
		for pidend in $pidlogs; do
			let i=i+1
		done
		if [[ -n "$pidend" ]]; then
			login="$(grep "$pid" "$log" 2>/dev/null | grep "$pidend" | grep "$loginsukses")"
			PID=$pid
			user="$(echo "$login" | awk -F" " '{print $10}' | sed -r "s/'/ /g")"
			waktu="$(echo "$login" | awk -F" " '{print $2"-"$1,$3}')"
			while [[ ${#waktu} -lt 13 ]]; do waktu="${waktu} "; done
			while [[ ${#user} -lt 16 ]]; do user="${user} "; done
			while [[ ${#PID} -lt 8 ]]; do PID="${PID} "; done
			echo "$user $PID $waktu"
		fi
	done
}

line
echo -e "${SSHPLUS_CYAN}\033[1mUSUARIOS:          ESTADO:       CONECTADOS:       TIEMPO:\033[0m"
line

found=0
row=0
while read -r usline; do
	user="$(echo "$usline" | awk '{print $1}')"
	s2ssh="$(echo "$usline" | awk '{print $2}')"
	[[ "$s2ssh" =~ ^[0-9]+$ ]] || s2ssh=1
	valid_sshplus_user "$user" || continue
	found=1
	row=$((row + 1))

	if getent passwd "$user" >/dev/null 2>&1; then
		sqd="$(ps -u "$user" | grep sshd | wc -l)"
	else
		sqd=0
	fi
	[[ -z "$sqd" ]] && sqd=0

	if [[ -e /etc/openvpn/openvpn-status.log ]]; then
		ovp="$(grep -E ,"$user", /etc/openvpn/openvpn-status.log | wc -l)"
	else
		ovp=0
	fi

	if netstat -nltp 2>/dev/null | grep 'dropbear' >/dev/null; then
		drop="$(fun_drop | grep "$user" | wc -l)"
	else
		drop=0
	fi

	cnx=$((sqd + drop))
	conex=$((cnx + ovp))
	if [[ $cnx -gt 0 ]]; then
		tst="$(ps -o etime "$(ps -u "$user" | grep sshd | awk 'NR==1 {print $1}')" 2>/dev/null | awk 'NR==2 {print $1}')"
		tst1=$(echo "$tst" | wc -c)
		if [[ "$tst1" == "9" ]]; then
			timerr="$tst"
		else
			timerr="00:$tst"
		fi
	elif [[ $ovp -gt 0 ]]; then
		tmp2=$(printf '%(%H:%M:%S)T\n')
		tmp1="$(grep -w "$user" /etc/openvpn/openvpn-status.log | awk '{print $4}' | head -1)"
		[[ -z "$tmp1" ]] && tmp1="00:00:00" && tmp2="00:00:00"
		var1="$(echo "$tmp1" | cut -c 1-2)"
		var2="$(echo "$tmp1" | cut -c 4-5)"
		var3="$(echo "$tmp1" | cut -c 7-8)"
		var4="$(echo "$tmp2" | cut -c 1-2)"
		var5="$(echo "$tmp2" | cut -c 4-5)"
		var6="$(echo "$tmp2" | cut -c 7-8)"
		calc1="$(echo "$var1*3600 + $var2*60 + $var3" | bc)"
		calc2="$(echo "$var4*3600 + $var5*60 + $var6" | bc)"
		seg=$((calc2 - calc1))
		min=$((seg / 60))
		seg=$((seg - min * 60))
		hor=$((min / 60))
		min=$((min - hor * 60))
		timerusr="$(printf "%02d:%02d:%02d \n" "$hor" "$min" "$seg")"
		timerr="$(echo "$timerusr" | sed -e 's/[^0-9:]//ig')"
	else
		timerr="00:00:00"
	fi

	printf ' %b[%s]\033[0m \033[1;37m> \033[1;33m%-12s\033[0m' "$SSHPLUS_NUM" "$row" "$user"
	if [[ $conex -eq 0 ]]; then
		printf '\033[1;31mo\033[0m'
	else
		printf '\033[1;32mo\033[0m'
	fi
	printf '            \033[1;33m%-14s%s\033[0m\n' "$conex/$s2ssh" "$timerr"
done < "$database"

[[ "$found" -eq 0 ]] && echo -e "\033[1;33mNo hay usuarios SSH creados por la script.\033[0m"
line
echo -e " ${SSHPLUS_NUM}[0]\033[0m \033[1;37m> VOLVER\033[0m"
line
echo -ne "\033[1;32mOpcion\033[1;33m: \033[0m"; read -r _back
